sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t indrajeetrai@gmail.com/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true indrajeetrai@gmail.com/docker-react npm run test
  
 deploy:
    provider:elasticbeanstalk
    region:"us-east-1"
    app:"docker-react"
    env:"DockerReact-env"
    bucket_name:"elasticbeanstalk-us-east-1-190799944449"
    bucket_path:"docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure:"$SECRET_ACCESS_KEY"